# Default: 90
# Range: 0 ~ 100
showWindParticles = 90
# Default: 10
# Range: 0 ~ 100
minEctoMistEffectRadius = 10

[HUD]
	leftEffectIcon = false
	# Default: 0
	# Range: -256 ~ 256
	extraInventoryButtonOffsetX = 192
	# Default: 0
	# Range: -256 ~ 256
	extraInventoryButtonOffsetY = 0

	[HUD.Health]
		terraStyleHealth = true
		#Allowed Values: LEGACY, OVERLAY
		healthStyle = "OVERLAY"
		# Default: 0
		# Range: -256 ~ 256
		healthOffsetX = 0
		# Default: 0
		# Range: -256 ~ 256
		healthOffsetY = 0

	[HUD.Food]
		terraStyleFood = false
		#Allowed Values: LEGACY, OVERLAY
		foodStyle = "OVERLAY"

	[HUD.Mana]
		#Allowed Values: LEGACY, OVERLAY
		manaStyle = "OVERLAY"
		# Default: 0
		# Range: -256 ~ 256
		manaOffsetX = 0
		# Default: 0
		# Range: -256 ~ 256
		manaOffsetY = 0

	[HUD.Armor]
		terraStyleArmor = true
		#Allowed Values: LEGACY_HORIZONTAL, LEGACY_DIAGONAL, LEGACY_VERTICAL, OVERLAY
		armorStyle = "OVERLAY"

	[HUD.Boss]
		#Allowed Values: VANILLA, STATIC, DYNAMIC
		bossBarStyle = "STATIC"
		#Show exact health values on custom boss bars.
		bossBarNumbersVisible = true

[Entity]
	bloodyEffect = true
	#Allowed Values: OFF, CONFLUENCE, CONFLUENCE_VANILLA, ALL
	goreEffect = "ALL"
	#Allowed Values: PARTICLE, VIRTUAL
	damageIndicator = "VIRTUAL"
	#Allowed Values: PARTICLE, VIRTUAL
	healIndicator = "VIRTUAL"

[GUI]
	achievementToast = true
	#Allowed Values: NEVER, EVERYWHERE, TRADE_SCREEN
	sellPriceDisplay = "EVERYWHERE"
	# Default: 71
	# Range: 0 ~ 1000
	customTitle = 71
	#显示武器自身的伤害和暴击率（保留词缀），不计玩家装备和效果加成；默认显示加成后的数值。
	weaponTooltipBaseStats = false

	[GUI.Soulcerer]
		# Default: 270
		# Range: 0 ~ 360
		soulcererBackgroundHue = 270
		# Default: 255
		# Range: 0 ~ 255
		soulcererBackgroundContrast = 255
		soulcererBackgroundTree = true
		soulcererBackgroundMagic = true

	[Biome."The Hallow"]
		# Default: 3
		# Range: 0 ~ 20
		rainbowCount = 3
		rainbowGradient = false

[WeaponInput]
	#Allowed Values: LEFT, RIGHT
	staffUseButton = "RIGHT"
	#Allowed Values: LEFT, RIGHT
	whipUseButton = "LEFT"
	#Allowed Values: LEFT, RIGHT
	yoyoUseButton = "LEFT"
	#Allowed Values: LEFT, RIGHT
	gunUseButton = "LEFT"
	#Allowed Values: LEFT, RIGHT
	flailUseButton = "LEFT"
