# Default: -1
# Range: -9223372036854775808 ~ 9223372036854775807
modifyTime = 1767545160363
version = "1.2.0"
messageDigest = "$1$tur3m1an$wr/xFfQPjNJ8sbcXp/fz1/"
# Default: -1
# Range: > -2147483648
alarmTimes = 3
attributeReplacements = ["crit_chance = confluence_magic_lib:generic.critical_chance", "ranged_damage = confluence_magic_lib:generic.ranged_damage", "dodge_chance = confluence_magic_lib:generic.dodge_chance", "magic_damage = confluence_magic_lib:generic.magic_damage", "armor_penetration = confluence_magic_lib:generic.armor_penetration"]
itemGroups = true
