#This file stores configuration options for Iris, such as the currently active shaderpack
#Mon Aug 17 21:40:21 CEST 2026
allowUnknownShaders=true
colorSpace=SRGB
disableUpdateMessage=false
enableDebugOptions=false
enableShaders=true
maxShadowRenderDistance=4
shaderPack=Solar Shader v1.6.1.zip
