#This file stores configuration options for Iris, such as the currently active shaderpack
#Fri Jul 24 16:48:33 CEST 2026
allowUnknownShaders=true
colorSpace=SRGB
disableUpdateMessage=false
enableDebugOptions=false
enableShaders=false
maxShadowRenderDistance=4
shaderPack=\u00A7lE-LITE shaders 5.1.1.zip
