affiliateUrl = "https://billing.kinetichosting.com/aff.php?aff=956"
useTranslation = false
bannerLine1 = "&f  Affordable Hosting — Support NeoTech Reborn!"
bannerLine2 = "&a&lClick to use my affiliate link!"
