version = 1
enableSodiumMenu = true
cloudCulling = true
signTextCulling = true
rainCulling = true
dontCull = []
useBlockStateCulling = true
useCustomItemFrameRenderer = true
itemFrameMapCulling = true
useItemFrameLOD = true
itemFrameLODRange = 16
useItemFrame3FaceCulling = true
itemFrame3FaceCullingRange = 2.0
paintingCulling = true
leavesCullingMode = "FAST"
leavesCullingAmount = 1
includeMangroveRoots = true
endGatewayCulling = true
beaconBeamCulling = true
useOnModdedBlocksByDefault = true

[modCompatibility]
enderio = true
mcwfences = true
fastitemframes = true
spelunkers_charm = true
farmersdelight = true
mob_grinding_utils = true
mcwbyg = true
simplemagnets = true
create_easy_structures = true
cookingforblockheads = true
jitl = true
croptopia = true
vampiresdelight = true
bigger_ae2 = true
redstonepen = true
silentgear = true
mcwstairs = true
pointblank = true
dungeonsdelight = true
ecologics = true
copycats = true
allthemodium = true
visualoverhaul = true
advanced_ae = true
comforts = true
irons_jewelry = true
domum_ornamentum = true
yigd = true
woodwevegot = true
aether = true
morered = true
prefab = true
the_bumblezone = true
functionalstorage = true
craftingstation = true
bankstorage = true
ftbquests = true
the_pillager_legion_ = true
jaopca = true
chisel = true
reanimal = true
productivetrees = true
magnumtorch = true
fargostalismans = true
l2complements = true
hybrid-aquatic = true
valhelsia_furniture = true
darkblades = true
endersdelight = true
netherex = true
tinymultiblocklib = true
apotheosis = true
trophymanager = true
create = true
deeperdarker = true
divinerpg = true
vampirism = true
minersdelight = true
doggytalents = true
culturaldelights = true
yungscavebiomes = true
buildinggadgets2 = true
minecolonies = true
biomeswevegone = true
additionallanterns = true
glassential = true
sfm = true
visualworkbench = true
multipiston = true
easy_villagers = true
rusticdelight = true
mcwfurnitures = true
sophisticatedstorage = true
waystones = true
additional_lights = true
aquaculturedelight = true
earthmobsmod = true
apothic_enchanting = true
animal_pen = true
born_in_chaos_v1 = true
pipez = true
expandeddelight = true
disenchanting_table = true
tide = true
framedblocks = true
fishofthieves = true
megacells = true
ribbits = true
easymagic = true
hostilenetworks = true
quark = true
mcwquark = true
irons_spellbooks = true
youkaishomecoming = true
gobber2 = true
selling_bin = true
more_beautiful_torches = true
mcwlights = true
mcwholidays = true
earthtojavamobs = true
block_factorys_bosses = true
globalxp = true
livingthings = true
pneumaticcraft = true
rootsclassic = true
mekanismadditions = true
mcwdoors = true
terra_entity = true
sushigocrafting = true
valhelsia_structures = true
factory_blocks = true
mekanism = true
pfw_aesthetic_gems = true
umbral_skies = true
arsdelight = true
deep_aether = true
utilitarian = true
trashcans = true
wildernature = true
ars_ocultas = true
create_dragons_plus = true
mininggadgets = true
tombstone = true
ars_additions = true
merequester = true
extradelight = true
industrialization_overdrive = true
betterblockz = true
storagenopoof = true
ae2 = true
undergardendelight = true
randomore = true
bosses_of_mass_destruction = true
monolib = true
irons_patreon_lib = true
ars_nouveau = true
crabbersdelight = true
productivebees = true
meadow = true
enemybanner = true
fluxnetworks = true
javd = true
azurelib = true
mutantmonsters = true
butcher = true
moresnifferflowers = true
excavated_variants = true
withersweapons = true
geosmelt = true
lendersdelight = true
arseng = true
friendsandfoes = true
easyanvils = true
refurbished_furniture = true
pamhc2crops = true
ironbookshelves = true
actuallyadditions = true
evilcraft = true
duckling = true
powah = true
ars_technica = true
piglet_structures = true
mcwbridges = true
ferdinandsflowers = true
arcaneessenceblock = true
bloomingnature = true
handcrafted = true
mynethersdelight = true
thaumon = true
bloodlines = true
botanypotstiers = true
rechiseledcreate = true
eternalnether = true
modern_industrialization = true
ars_creo = true
occultismdelight = true
knightlib = true
aoa3 = true
twilightdelight = true
dndesires = true
homesteads = true
naturalist = true
easy_emerald = true
supplementaries = true
trofers = true
bno = true
twilight_lootr = true
beachparty = true
endrem = true
silentgems = true
projectvibrantjourneys = true
frightsdelight = true
rottencreatures = true
createenchantablemachinery = true
ancientreforging = true
minecraft = true
enderzoology = true
occultism = true
extrasponges = true
mowziesmobs = true
undergarden = true
starcatcher = true
cuisinedelight = true
createaddition = true
ceilingtorch = true
werewolves = true
travelersbackpack = true
dumplings_delight = true
twilightforest = true
butchercraft = true
creeperoverhaul = true
cursedearth = true
gag = true
xtonesreworked = true
hammerlib = true
easy_piglins = true
charginggadgets = true
ironfurnaces = true
immersiveengineering = true
mobs_of_mythology = true
illagerinvasion = true
koopascritters = true
luminous_nether = true
compatapi = true
mcwroofs = true
darkerdepths = true
mctb = true
eternal_starlight = true
enhanced_enchanting = true
mysticalagradditions = true
mcwwindows = true
wildex = true
piglinproliferation = true
storagedelight = true
oceansdelight = true
securitycraft = true
cataclysm = true
mysticalagriculture = true
diagonalwalls = true
farmingforblockheads = true
netherskeletons = true
mcwpaths = true
simplylight = true
create_enchantment_industry = true
luckytntmod = true
bellsandwhistles = true
fastpaintings = true
mcwtrpdoors = true
mekanismgenerators = true
botanypots = true
amendments = true
fruitsdelight = true
extended_industrialization = true
diagonalfences = true
moonlight = true
advancednetherite = true
relics = true
morevillagers = true
sophisticatedbackpacks = true
appflux = true
iron_ender_chests = true
crystalcraft_unlimited_java = true
cratedelight = true
terra_curio = true
ascended_quark = true
ubesdelight = true
theurgy = true
undead_revamp2 = true
chipped = true
hyperbox = true
aquaculture = true
structurize = true
beo = true
justdirethings = true
luminousworld = true
sereneseasons = true
stardew_fishing = true
modularrouters = true
terra_furniture = true
lootr = true
regions_unexplored = true
iceandfire = true
expandedstorage = true
irons_lib = true
stickit = true
betterarcheology = true
youkaisfeasts = true
endermanoverhaul = true
knightquest = true
ars_elemental = true
forbidden_arcanus = true
pamhc2trees = true
confluence = true
computercraft = true
moderndynamics = true
geore = true
sauce = true
crittersandcompanions = true
barbequesdelight = true
extendedae = true
l2hostility = true
enchantinginfuser = true
netherdepthsupgrade = true
rechiseled = true
mcwregionsunexplored = true
